
post https://node-api-videos-5d9d.onrender.com/videos
Content-Type: application/json

{
    "title": "title 1",
    "description": "descrição 1",
    "duration": 11
}

###
get https://node-api-videos-5d9d.onrender.com/videos
###

PUT  http://localhost:3000/videos/6f7c1156-166b-4431-acce-ed17da071507
Content-Type: application/json

{
    "title": "title 2",
    "description": "descrição 2? ",
    "duration": 3215
    }

###
DELETE http://localhost:3000/videos/2dee6bf7-0522-4636-8270-97957bf7a79a

###
DELETE http://localhost:3000/videos/delete