
post https://node-api-videos-5d9d.onrender.com/videos
Content-Type: application/json

{
    "title": "teste remoto 1",
    "description": "descrição  remota 1",
    "duration": 11
}

###
get https://node-api-videos-5d9d.onrender.com/videos
###

PUT  https://node-api-videos-5d9d.onrender.com/videos/idperso
Content-Type: application/json

{
    "title": "id manual",
    "description": "tre 2? ",
    "duration": 1
    }

###
DELETE https://node-api-videos-5d9d.onrender.com/videos/cb47c6ac-8f08-4ff9-87e9-2ead84340e9d

###
DELETE https://node-api-videos-5d9d.onrender.com/videos/delete